name = "butaneprotocol/subledger"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'butaneprotocol/subledger'"

[repository]
user = "butaneprotocol"
project = "subledger"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
